
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

typedef struct glimage_bindings_Image glimage_bindings_Image;
typedef struct T_Result_Bool_String Result_Bool_String;
enum E_Result {
  E_Ok,
  E_Error
};
union U_Result_Bool_String {
  struct Ok_Bool_String *Ok;
  struct Error_Bool_String *Error;
};
struct T_Result_Bool_String {
  enum E_Result tag;
  union U_Result_Bool_String val;
};
struct glimage_bindings_Image {
  Int w;
  Int h;
  String data;
  Int channels;
};
struct Ok_Bool_String {
  Bool value;
};
struct Error_Bool_String {
  String value;
};


glimage_bindings_Image new_glimage_bindings_Image(Int w, Int h, String data, Int channels);
Bool eq_glimage_bindings_Image(glimage_bindings_Image a, glimage_bindings_Image b);
Bool lt_glimage_bindings_Image(glimage_bindings_Image a, glimage_bindings_Image b);
String inspect_glimage_bindings_Image(glimage_bindings_Image value);
Result_Bool_String new_Ok_Bool_String(Bool value);
Result_Bool_String new_Error_Bool_String(String value);
Bool eq_Result_Bool_String(Result_Bool_String a, Result_Bool_String b);
Bool lt_Result_Bool_String(Result_Bool_String a, Result_Bool_String b);
String inspect_Result_Bool_String(Result_Bool_String value);
Result_Bool_String glimage_stbi_write_png(glimage_bindings_Image image, String filename);
glimage_bindings_Image glimage_stbi_load(String filename);